
<a href="<?php echo $this->url('region',array('controller'=>'Index', 'action'=>'add')) ?>"><?php echo "Ajouter" ?></a>

 <table class="table">
     <tr>
     	 <th>Region Id</th>
         <th>Region Label</th>
         <th>Region Weight</th>
         <th>&nbsp;</th>
     </tr>
     <?php foreach ($this->paginator as $region) : ?>
         <tr>
          <td><?php echo $this->escapeHtml($region->_regionId);?></td>
             <td><?php echo $this->escapeHtml($region->_regionLabel);?></td>
             <td><?php echo $this->escapeHtml($region->_regionWeight);?></td>
             <td><a href="<?php echo $this->url('region',array('controller'=>'Index', 'action'=>'edit','id'=> $region->_regionId)) ?>"><?php echo "edit" ?></a></td>
             <td><a href="<?php echo $this->url('region',array('controller'=>'Index', 'action'=>'delete','id'=> $region->_regionId)) ?>"><?php echo "delete" ?></a></td>
             
         </tr>
     <?php endforeach; ?>
 </table>

<?php
echo $this->paginationControl(
    // the paginator object
    $this->paginator,
    // the scrolling style; see http://zf2.readthedocs.org/en/release-2.1.4/modules/zend.paginator.usage.html#rendering-pages-with-view-scripts
    'sliding',
    // the partial to use to render the control
    array('partial/pagination.phtml', 'Region'),
    // the route to link to when a user clicks a control link
    array(
        'route' => 'region'
    )
);
?>
<h2>Images flickr :</h2>
<hr/>
<?php
    foreach($this->photos as $photo){
        echo "<img src='http://farm".$photo['farm'].".staticflickr.com/".$photo['server']."/".$photo['id']."_".$photo['secret'].".jpg' />";
    }
?>
